src/Entity/Forcast.php
<?php

namespace App\Entity;

use App\Repository\ForcastRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ForcastRepository::class)]
class Forcast
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $temperature = null;

    #[ORM\ManyToOne(inversedBy: 'forcasts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column]
    private ?float $feels_like_temp = null;

    #[ORM\Column]
    private ?int $humidity = null;

    #[ORM\Column]
    private ?int $wind_speed = null;

    #[ORM\Column]
    private ?int $precipation_probability = null;

    #[ORM\Column(nullable: true)]
    private ?float $precipation = null;

    #[ORM\Column]
    private ?int $atmospheric_pressure = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTemperature(): ?float
    {
        return $this->temperature;
    }

    public function setTemperature(float $temperature): static
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getFeelsLikeTemp(): ?float
    {
        return $this->feels_like_temp;
    }

    public function setFeelsLikeTemp(float $feels_like_temp): static
    {
        $this->feels_like_temp = $feels_like_temp;

        return $this;
    }

    public function getHumidity(): ?int
    {
        return $this->humidity;
    }

    public function setHumidity(int $humidity): static
    {
        $this->humidity = $humidity;

        return $this;
    }

    public function getWindSpeed(): ?int
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(int $wind_speed): static
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getPrecipationProbability(): ?int
    {
        return $this->precipation_probability;
    }

    public function setPrecipationProbability(int $precipation_probability): static
    {
        $this->precipation_probability = $precipation_probability;

        return $this;
    }

    public function getPrecipation(): ?float
    {
        return $this->precipation;
    }

    public function setPrecipation(?float $precipation): static
    {
        $this->precipation = $precipation;

        return $this;
    }

    public function getAtmosphericPressure(): ?int
    {
        return $this->atmospheric_pressure;
    }

    public function setAtmosphericPressure(int $atmospheric_pressure): static
    {
        $this->atmospheric_pressure = $atmospheric_pressure;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getFahrenheit(): ?float
    {
        return $this->temperature * 9 / 5 + 32;
    }
}

src/Form/ForcastType.php
<?php

namespace App\Form;


use App\Entity\Forcast;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ForcastType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('temperature', NumberType::class,[
                'html5'=>true,
            ])
            ->add('feels_like_temp', NumberType::class,[
                'html5'=>true,
            ])
            ->add('humidity', NumberType::class,[
                'html5'=>true,
            ])
            ->add('wind_speed', NumberType::class,[
                'html5'=>true,
            ])
            ->add('precipation_probability', NumberType::class,[
                'html5'=>true,
            ])
            ->add('precipation', NumberType::class,[
                'html5'=>true,
                'required'=>false,
            ])
            ->add('atmospheric_pressure', NumberType::class,[
                'html5'=>true,
            ])
            ->add('date', DateType::class)
            ->add('location', EntityType::class, [
                'class' => 'App\Entity\Location',
                'choice_label' => 'city',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Forcast::class,
        ]);
    }
}

src/Controller/ForcastController.php
<?php

namespace App\Controller;

use App\Entity\Forcast;
use App\Form\ForcastType;
use App\Repository\ForcastRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/forcast')]
class ForcastController extends AbstractController
{
    #[Route('/', name: 'app_forcast_index', methods: ['GET'])]
    #[IsGranted('ROLE_FORCAST_INDEX')]
    public function index(ForcastRepository $forcastRepository): Response
    {
        return $this->render('forcast/index.html.twig', [
            'forcasts' => $forcastRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_forcast_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FORCAST_NEW')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $forcast = new Forcast();
        $form = $this->createForm(ForcastType::class, $forcast,[
            'validation_groups'=>'create',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($forcast);
            $entityManager->flush();

            return $this->redirectToRoute('app_forcast_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forcast/new.html.twig', [
            'forcast' => $forcast,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_forcast_show', methods: ['GET'])]
    #[IsGranted('ROLE_FORCAST_SHOW')]
    public function show(Forcast $forcast): Response
    {
        return $this->render('forcast/show.html.twig', [
            'forcast' => $forcast,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_forcast_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FORCAST_EDIT')]
    public function edit(Request $request, Forcast $forcast, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ForcastType::class, $forcast,[
            'validation_groups'=>'edit',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_forcast_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forcast/edit.html.twig', [
            'forcast' => $forcast,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_forcast_delete', methods: ['POST'])]
    #[IsGranted('ROLE_FORCAST_DELETE')]
    public function delete(Request $request, Forcast $forcast, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$forcast->getId(), $request->request->get('_token'))) {
            $entityManager->remove($forcast);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_forcast_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/forcast/_delete_form.html.twig
<form method="post" action="{{ path('app_forcast_delete', {'id': forcast.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ forcast.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/forcast/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/forcast/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Forcast{% endblock %}

{% block body %}
    <h1>Edit Forcast</h1>

    {{ include('forcast/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_forcast_index') }}">back to list</a>

    {{ include('forcast/_delete_form.html.twig') }}
{% endblock %}

templates/forcast/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forcast index{% endblock %}

{% block body %}
    <h1>Forcast index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Temperature</th>
                <th>Feels_like_temp</th>
                <th>Humidity</th>
                <th>Wind_speed</th>
                <th>Precipation_probability</th>
                <th>Precipation</th>
                <th>Atmospheric_pressure</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for forcast in forcasts %}
            <tr>
                <td>{{ forcast.id }}</td>
                <td>{{ forcast.temperature }}</td>
                <td>{{ forcast.feelsLikeTemp }}</td>
                <td>{{ forcast.humidity }}</td>
                <td>{{ forcast.windSpeed }}</td>
                <td>{{ forcast.precipationProbability }}</td>
                <td>{{ forcast.precipation }}</td>
                <td>{{ forcast.atmosphericPressure }}</td>
                <td>{{ forcast.date ? forcast.date|date('Y-m-d') : '' }}</td>
                <td>
                    {% if is_granted('ROLE_FORCAST_SHOW') %}
                    <a href="{{ path('app_forcast_show', {'id': forcast.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_FORCAST_EDIT') %}
                    <a href="{{ path('app_forcast_edit', {'id': forcast.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        {% if is_granted('ROLE_FORCAST_NEW') %}
        <a href="{{ path('app_forcast_new') }}">Create new</a>
        {% endif %}
{% endblock %}

templates/forcast/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Forcast{% endblock %}

{% block body %}
    <h1>Create new Forcast</h1>

    {{ include('forcast/_form.html.twig') }}

    <a href="{{ path('app_forcast_index') }}">back to list</a>
{% endblock %}

templates/forcast/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forcast{% endblock %}

{% block body %}
    <h1>Forcast</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ forcast.id }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ forcast.temperature }}</td>
            </tr>
            <tr>
                <th>Feels_like_temp</th>
                <td>{{ forcast.feelsLikeTemp }}</td>
            </tr>
            <tr>
                <th>Humidity</th>
                <td>{{ forcast.humidity }}</td>
            </tr>
            <tr>
                <th>Wind_speed</th>
                <td>{{ forcast.windSpeed }}</td>
            </tr>
            <tr>
                <th>Precipation_probability</th>
                <td>{{ forcast.precipationProbability }}</td>
            </tr>
            <tr>
                <th>Precipation</th>
                <td>{{ forcast.precipation }}</td>
            </tr>
            <tr>
                <th>Atmospheric_pressure</th>
                <td>{{ forcast.atmosphericPressure }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ forcast.date ? forcast.date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_forcast_index') }}">back to list</a>

    <a href="{{ path('app_forcast_edit', {'id': forcast.id}) }}">edit</a>

    {{ include('forcast/_delete_form.html.twig') }}
{% endblock %}